[package]
name = "pushmore"
description = "Easily send notifications to Telegram"
version = "0.1.1"
license = "MIT"
readme = "README.md"
authors = ["Daniel Lockyer <daniel@daniellockyer.com>"]
repository = "https://github.com/neosilky/pushmore-rust-client"
homepage = "https://github.com/neosilky/pushmore-rust-client"
keywords = ["telegram", "notifications"]

[badges]
travis-ci = { repository = "neosilky/pushmore-rust-client" }

[dependencies]
reqwest = "0.8"
